services:
  frontend:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - "backend"
    networks:
      - app-network  

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run start:dev
    environment:
      NODE_ENV: development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

